/**
 * CAMADA 1: FONTES EXTERNAS
 * MetaTrader 5, Binance, OANDA, BCB, Yahoo Finance
 */

// SETORES 001-028: B3 Ações/BDRs/Futuros/Commodities
export const B3_SYMBOLS = {
  // SETOR 001-010: Ações principais
  ACOES_PRINCIPAIS: [
    'PETR4', 'VALE3', 'ITUB4', 'BBDC4', 'ABEV3', 'WEGE3', 'RENT3', 'MGLU3',
    'BBAS3', 'SANB11', 'SUZB3', 'JBSS3', 'GGBR4', 'CSNA3', 'USIM5', 'CSAN3',
    'BRAP4', 'CMIG4', 'CPLE6', 'CPFE3', 'ELET3', 'ELET6', 'ENBR3', 'ENEV3',
    'EGIE3', 'EQTL3', 'TAEE11', 'TRPL4', 'BRKM5', 'BRFS3', 'CCRO3', 'CVCB3',
    'CYRE3', 'DIRR3', 'EZTC3', 'GFSA3', 'GNDI3', 'HAPV3', 'HYPE3', 'IGTI11',
    'IRBR3', 'ITSA4', 'JBSS3', 'KLBN11', 'LAME4', 'LREN3', 'MRFG3', 'MRVE3',
    'MULT3', 'PCAR3', 'PDGR3', 'PETR3', 'POMO4', 'POSI3', 'QUAL3', 'RADL3',
    'RAIL3', 'RECV3', 'SBSP3', 'SMTO3', 'SULA11', 'TIMS3', 'TOTS3', 'UGPA3',
    'VIVT3', 'VVAR3', 'WIZC3', 'YDUQ3', 'BBSE3', 'BPAC11', 'BPAN4', 'B3SA3',
    'ALPA4', 'ALSO3', 'AMAR3', 'ARZZ3', 'AZUL4', 'BEEF3', 'BIDI11', 'BIDI4',
    'BRML3', 'BTOW3', 'CAML3', 'CEAB3', 'CEDO4', 'CIEL3', 'COGN3', 'CRFB3',
    'CVCB3', 'DMMO3', 'DXCO3', 'ECOR3', 'EMBR3', 'ENAT3', 'ESTR4', 'FESA4',
    'FTRI3', 'GEPA4', 'GMAT3', 'GOAU4', 'GOLL4', 'GRND3', 'GUAR3', 'HBSA3',
    'INTB3', 'JHSF3', 'KEPL3', 'LIGA3', 'LINX3', 'LIPR3', 'LOGG3', 'LOGN3',
    'LUPA3', 'MDIA3', 'MEAL3', 'MGLU3', 'MOSI3', 'MWET4', 'NEOE3', 'ODPV3',
    'OFER3', 'OPCT3', 'ORVR3', 'OSXB3', 'PARD3', 'PATI4', 'PGCN3B', 'PLPL3',
    'PNVL3', 'PFRM3', 'PTBL3', 'PTNT4', 'QGEP3', 'QNET3', 'QVQP3B', 'RADL3',
    'RCSL4', 'RCSL3', 'RDOR3', 'REET3', 'RENT3', 'RNEW11', 'RNEW3', 'RNEW4',
    'RRRP3', 'RSID3', 'SANB11', 'SAPR11', 'SAPR4', 'SBFG3', 'SEER3', 'SGPS3',
    'SHOW3', 'SHUL4', 'SLCE3', 'SLED4', 'SMLS3', 'SNFE3', 'SNSY5', 'SPRI3',
    'SQIA3', 'STBP3', 'SYNE3', 'TANC11', 'TCNO3', 'TECN3', 'TEF3', 'TEF3',
    'TGMA3', 'TICK3', 'TINE3', 'TKNO3', 'TOYB3', 'TPIS3', 'TRAD3', 'TRFX3',
    'TRIS3', 'TUPY3', 'UCAS3', 'UGPA3', 'UNIP6', 'USIM3', 'USIM5', 'VAGR3',
    'VAMO3', 'VCTO3', 'VIVA3', 'VULC3', 'WEGE3', 'WHRL3', 'WIZC3', 'WIZS3',
    'WLCC4', 'WIZC3', 'YDUQ3', 'ZAMP3'
  ],
  // SETOR 011-020: Small Caps e BDRs
  SMALL_CAPS: [
    'AALR3', 'ABEV3', 'AMAR3', 'ANIM3', 'ARML3', 'ARZZ3', 'AURA33', 'AVLL3',
    'AZUL4', 'B3SA3', 'BAUH4', 'BBDC3', 'BBDC4', 'BBRK3', 'BBSE3', 'BDLL4',
    'BEEF3', 'BGIP4', 'BIDI11', 'BIDI4', 'BMEB4', 'BMGB4', 'BMIN4', 'BMOB3',
    'BNBR3', 'BOBR4', 'BPAC11', 'BPAC5', 'BPAN4', 'BRAP4', 'BRBI11', 'BRDT3',
    'BRFS3', 'BRGE12', 'BRGE3', 'BRKM5', 'BRML3', 'BRPR3', 'BRSR6', 'BTOW3',
    'BVMF3', 'CAML3', 'CARD3', 'CBMA4', 'CCRO3', 'CEBR6', 'CEDO4', 'CEEB5',
    'CEPE3', 'CESP6', 'CGAS5', 'CGRA4', 'CIQU4', 'CIEL3', 'CLSC4', 'CMIG3',
    'CMIG4', 'CNTO4', 'COCE5', 'COCE6', 'COGN3', 'CPFE3', 'CPLE3', 'CPLE5',
    'CPLE6', 'CPRE6', 'CRDE3', 'CRFB3', 'CRIV4', 'CRPG5', 'CSAB4', 'CSAN3',
    'CSED3', 'CSMG3', 'CSNA3', 'CSTB4', 'CTKA4', 'CTNM4', 'CVCB3', 'CYRE3',
    'DAGB33', 'DASA3', 'DCXU33', 'DIRR3', 'DMMO3', 'DOHL4', 'DTCY3', 'DUQE3',
    'DXCO3', 'ECAT3', 'Ecor3', 'EDGA3', 'EDMA4', 'ELEK4', 'ELET3', 'ELET6',
    'ELPL3', 'EMAE4', 'EMBR3', 'ENAT3', 'ENBR3', 'ENDI33', 'ENEV3', 'ENGI11',
    'ENG11', 'ENJH33', 'EQTL3', 'ESPA4', 'ESTR4', 'ETER3', 'EUCA4', 'EVEN3',
    'EZTC3', 'FCTB4', 'FHER3', 'FIEI3', 'FJTA4', 'FLCL3', 'FLRY3', 'FNCN3B',
    'FRTA3', 'FRXA33', 'FUGR4', 'FUND12', 'FUND3', 'FUND5', 'GEPA4', 'GGBR4',
    'GGBR3', 'GNDI3', 'GOAU4', 'GOLL4', 'GPCP3', 'GPSC3', 'GRND3', 'GSHP3',
    'GUAR3', 'HBRE3', 'HBSA3', 'HETA4', 'HGCL3', 'HGPO3', 'HGRU11', 'HYPE3',
    'IDNT3', 'IGBR3', 'IGTA3', 'IGTI11', 'INEP3', 'INTB3', 'IRBR3', 'ITSA3',
    'ITSA4', 'ITUB3', 'ITUB4', 'JALL3', 'JBSS3', 'JFEN3', 'JHSF3', 'JOPA3',
    'JPSF3', 'KEPL3', 'KLBN11', 'KLBN4', 'KROT4', 'LAME3', 'LAME4', 'LCAM3',
    'LEVE3', 'LFFT3', 'LIGA3', 'LINX3', 'LIPR3', 'LIVE3', 'LLIS3', 'LMER3',
    'LREN3', 'LUPA3', 'LWSA3', 'MAGG3', 'MAPT4', 'MBLY3', 'MDIA3', 'MEAL3',
    'MEDI3', 'MEGA3', 'MGLU3', 'MILS3', 'MIST11', 'MITS33', 'MMXM3', 'MNDL3',
    'MOAR3', 'MOSI3', 'MPTA4', 'MRFG3', 'MRVE3', 'MSAN3', 'MTRE3', 'MTSA4',
    'MULT3', 'MWET4', 'NAFG3', 'NAKP3', 'NATU3', 'NEOE3', 'NGRD3', 'NIPE3',
    'NMHI3', 'NUTR3', 'ODPV3', 'OFER3', 'OGMN3', 'OIBR3', 'OIBR4', 'OPCT3',
    'ORVR3', 'OSXB3', 'OXER3', 'PARD3', 'PATI3', 'PATI4', 'PBRA3', 'PBRA5',
    'PCAR3', 'PDGR3', 'PEAB4', 'PETR3', 'PETR4', 'PFRM3', 'PGCN3B', 'PINE4',
    'PLAS3', 'PLPL3', 'PMAM3', 'PNFV3', 'PNVL3', 'POMO4', 'POSI3', 'PPAR3',
    'PRBC4', 'PRIO3', 'PRSR3', 'PTBL3', 'PTNT4', 'QGEP3', 'QNET3', 'QVQP3B',
    'RADL3', 'RAIL3', 'RANI3', 'RANI4', 'RCSL3', 'RCSL4', 'RDOR3', 'REET3',
    'RENT3', 'RECV3', 'RNEW11', 'RNEW3', 'RNEW4', 'ROMI3', 'RRRP3', 'RSAN3',
    'RSCP4', 'RSID3', 'RUMO3', 'RZAT4', 'SANB11', 'SANB3', 'SANB4', 'SAPR11',
    'SAPR4', 'SBAP3', 'SBFG3', 'SBMO3', 'SBSP3', 'SCAR3', 'SCLO3', 'SEAB3',
    'SEER3', 'SEIV3', 'SEIV4', 'SGEN33', 'SGPS3', 'SHUL4', 'SHOW3', 'SLED4',
    'SLCE3', 'SLFG3', 'SMLS3', 'SMTR3', 'SMTO3', 'SNES3', 'SNFE3', 'SNSY5',
    'SODB3', 'SOMA3', 'SPAR3', 'SPRI3', 'SPTW3', 'SQIA3', 'SRNA3', 'SSPA3',
    'STAP3', 'STBP3', 'STDR3', 'SULA11', 'SULA3', 'SULA4', 'SUZB3', 'SWET3',
    'SYNE3', 'TAEE11', 'TAEE3', 'TAEE4', 'TANC11', 'TASA4', 'TBLE3', 'TCNO3',
    'TECN3', 'TEF3', 'TEF4', 'TELB4', 'TERI3', 'TGMA3', 'TIET11', 'TIET3',
    'TIET4', 'TICK3', 'TIMS3', 'TINE3', 'TITR12', 'TKNO3', 'TOTS3', 'TOYB3',
    'TPIS3', 'TRAD3', 'TRAD4', 'TRFX3', 'TRIS3', 'TRPL3', 'TRPL4', 'TSIM3',
    'TUPY3', 'UCAS3', 'UGAR3', 'UGPA3', 'UGPA4', 'UNIP6', 'USIM3', 'USIM5',
    'USIM6', 'VAGR3', 'VAMO3', 'VAPT3', 'VCAS3', 'VCTO3', 'VECT3', 'VGIR11',
    'VGRA3', 'VIBR3', 'VIVA3', 'VIVR3', 'VIVT3', 'VIVA3', 'VULC3', 'VVAR3',
    'VVAR4', 'WEGE3', 'WEGE4', 'WHRL3', 'WLCC4', 'WIZC3', 'WIZS3', 'WSON33',
    'XPCM3', 'YAMAB3', 'YDUQ3', 'ZAMP3'
  ],
  // SETOR 021-028: Commodities e Futuros
  FUTUROS_COMMODITIES: [
    'WINFUT', 'WINFUT1', 'WDOFUT', 'WDOFUT1', 'WSPFUT', 'WSPFUT1',
    'INDFUT', 'INDFUT1', 'BGI', 'CCM', 'ICF', 'SFI', 'TFC', 'TCM',
    'WET', 'WGC', 'WHE', 'WHG', 'WIG', 'WIP', 'WIT', 'WMG', 'WMT',
    'WOF', 'WPG', 'WPP', 'WPR', 'WRA', 'WRG', 'WSA', 'WSF', 'WSG',
    'WSI', 'WSL', 'WSM', 'WSN', 'WSO', 'WSP', 'WSS', 'WST', 'WSU',
    'WSW', 'WTG', 'WTH', 'WTI', 'WTL', 'WTM', 'WTN', 'WTO', 'WTP',
    'WTR', 'WTS', 'WTT', 'WTU', 'WTV', 'WTW', 'WTX', 'WTY', 'WTZ'
  ]
};

// SETOR 029: Cripto Spot (Binance)
export const CRYPTO_SYMBOLS = {
  PRINCIPAIS: [
    'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'ADAUSDT', 'DOGEUSDT',
    'SOLUSDT', 'DOTUSDT', 'MATICUSDT', 'LTCUSDT', 'SHIBUSDT', 'TRXUSDT',
    'AVAXUSDT', 'LINKUSDT', 'ATOMUSDT', 'UNIUSDT', 'XLMUSDT', 'BCHUSDT',
    'FILUSDT', 'NEARUSDT', 'APTUSDT', 'ARBUSDT', 'OPUSDT', 'INJUSDT',
    'SUIUSDT', 'SEIUSDT', 'TIAUSDT', 'BLURUSDT', 'IMXUSDT', 'RNDRUSDT',
    'FETUSDT', 'GRTUSDT', 'AAVEUSDT', 'MKRUSDT', 'SNXUSDT', 'COMPUSDT',
    'SUSHIUSDT', 'YFIUSDT', 'CRVUSDT', '1INCHUSDT', 'ZRXUSDT', 'KNCUSDT',
    'ENJUSDT', 'MANAUSDT', 'SANDUSDT', 'AXSUSDT', 'GALAUSDT', 'ENJUSDT',
    'CHZUSDT', 'BATUSDT', 'OCEANUSDT', 'BANDUSDT', 'ALGOUSDT', 'VETUSDT',
    'HBARUSDT', 'ICPUSDT', 'FTMUSDT', 'GRTUSDT', 'LRCUSDT', 'CELOUSDT',
    'STORJUSDT', 'SKLUSDT', 'KAVAUSDT', 'RUNEUSDT', 'CAKEUSDT', 'DYDXUSDT',
    'PERPUSDT', 'RSRUSDT', 'UMAUSDT', 'KSMUSDT', 'ZECUSDT', 'DASHUSDT',
    'EOSUSDT', 'ONTUSDT', 'ICXUSDT', 'QTUMUSDT', 'WAVESUSDT', 'ZILUSDT',
    'IOSTUSDT', 'STEEMUSDT', 'HIVEUSDT', 'BTSUSDT', 'SCUSDT', 'XEMUSDT',
    'DCRUSDT', 'LSKUSDT', 'LUNAUSDT', 'LUNCUSDT', 'BATUSDT', 'XMRUSDT',
    'DGBUSDT', 'ETCUSDT', 'XDCUSDT', 'HOTUSDT', 'HOLYUSDT', 'STMXUSDT',
    'SCUSDT', 'NPXSUSDT', 'MFTUSDT', 'KEYUSDT', 'DOCKUSDT', 'POLYUSDT',
    'PHXUSDT', 'HCUSDT', 'GOUSDT', 'TROYUSDT', 'VTHOUSDT', 'FTTUSDT',
    'SRMUSDT', 'RAYUSDT', 'STEPUSDT', 'ATLASUSDT', 'POLISUSDT', 'FIDAUSDT',
    'AUDIOUSDT', 'COCOUSDT', 'TULIPUSDT', 'GHIUSDT', 'SLIMUSDT', 'DAIUSDT',
    'USDCUSDT', 'USDPUSDT', 'TUSDUSDT', 'BUSDUSDT', 'FDUSDUSDT', 'PYUSDUSDT'
  ],
  BRAZILIAN: [
    'BTCBRL', 'ETHBRL', 'BNBBRL', 'SOLBRL', 'XRPAUD', 'ADAUDT', 'DOGEAUD'
  ]
};

// SETOR 039: Forex (28 Pares)
export const FOREX_PAIRS = {
  MAJORS: [
    'EURUSD', 'GBPUSD', 'USDJPY', 'USDCHF', 'AUDUSD', 'USDCAD', 'NZDUSD'
  ],
  CROSSES: [
    'EURGBP', 'EURJPY', 'EURCHF', 'EURAUD', 'EURCAD', 'EURNZD',
    'GBPJPY', 'GBPCHF', 'GBPAUD', 'GBPCAD', 'GBPNZD',
    'AUDJPY', 'AUDCHF', 'AUDCAD', 'AUDNZD',
    'CADJPY', 'CADCHF',
    'NZDJPY', 'NZDCHF', 'NZDCAD',
    'CHFJPY'
  ],
  EXOTICS: [
    'USDBRL', 'USDTRY', 'USDZAR', 'USDMXN', 'USDNOK', 'USDSEK', 'USDPLN',
    'USDSGD', 'USDHKD', 'USDDKK', 'USDHUF', 'USDCZK', 'USDILS', 'USDRON'
  ]
};

// SETOR 048: Taxas de Referência (BCB - SGS)
export const BCB_INDICATORS = {
  TAXAS: ['SELIC', 'CDI', 'IPCA', 'IGP-M', 'IGP-DI', 'INPC', 'IPC-FIPE'],
  CAMBIO: ['PTAX', 'USD_BRL', 'EUR_BRL'],
  CREDITO: ['TJLP', 'TR', 'POUPANCA', 'TLP']
};

// SETOR 052: Índices Globais (Yahoo Finance)
export const GLOBAL_INDICES = {
  AMERICAS: ['^GSPC', '^DJI', '^IXIC', '^RUT', '^VIX', '^BVSP', '^MXX'],
  EUROPE: ['^GDAXI', '^FTSE', '^FCHI', '^IBEX', '^FTMIB', '^AEX'],
  ASIA: ['^N225', '^HSI', '^AXJO', '^KS11', '^SSMI', '^STI', '^BSESN'],
  COMMODITIES: ['GC=F', 'SI=F', 'CL=F', 'NG=F', 'ZC=F', 'ZS=F', 'ZW=F']
};

// Total de símbolos por fonte
export const SYMBOL_COUNTS = {
  B3_ACOCES: B3_SYMBOLS.ACOES_PRINCIPAIS.length + B3_SYMBOLS.SMALL_CAPS.length,
  B3_FUTUROS: B3_SYMBOLS.FUTUROS_COMMODITIES.length,
  CRYPTO: CRYPTO_SYMBOLS.PRINCIPAIS.length + CRYPTO_SYMBOLS.BRAZILIAN.length,
  FOREX: FOREX_PAIRS.MAJORS.length + FOREX_PAIRS.CROSSES.length + FOREX_PAIRS.EXOTICS.length,
  BCB: BCB_INDICATORS.TAXAS.length + BCB_INDICATORS.CAMBIO.length + BCB_INDICATORS.CREDITO.length,
  GLOBAL: GLOBAL_INDICES.AMERICAS.length + GLOBAL_INDICES.EUROPE.length + GLOBAL_INDICES.ASIA.length + GLOBAL_INDICES.COMMODITIES.length
};

// Todos os símbolos em um array
export const ALL_SYMBOLS = [
  ...B3_SYMBOLS.ACOES_PRINCIPAIS,
  ...B3_SYMBOLS.SMALL_CAPS,
  ...B3_SYMBOLS.FUTUROS_COMMODITIES,
  ...CRYPTO_SYMBOLS.PRINCIPAIS,
  ...CRYPTO_SYMBOLS.BRAZILIAN,
  ...FOREX_PAIRS.MAJORS,
  ...FOREX_PAIRS.CROSSES,
  ...FOREX_PAIRS.EXOTICS,
  ...GLOBAL_INDICES.AMERICAS,
  ...GLOBAL_INDICES.EUROPE,
  ...GLOBAL_INDICES.ASIA,
  ...GLOBAL_INDICES.COMMODITIES
];

console.log(`[NEXUS-CORE] 📊 Total de símbolos: ${ALL_SYMBOLS.length}`);
